# -*- coding: utf-8 -*-
"""k-mean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17CMpSrJswUHWowevwyVQ4w2Rqnooc6Xv
"""

from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/data_2023-04-02.csv')

latitude_list= df['Latitude']
longitude_list = df['Longitude']

df.head()
#latitude_list.head()

#X = np.column_stack((latitude_list, longitude_list))

x=df[["Latitude","Longitude"]]

x.head()

kmeans = KMeans(n_clusters=3)

# Fit the model to your data
y_kmeans=kmeans.fit_predict(x)

y_kmeans

df['y']=y_kmeans
df.head()

plt.scatter(df['Latitude'],df['Longitude'],c=df['y'])

